# Generated by Django 4.1 on 2024-06-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
