# Generated by Django 4.1 on 2024-06-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_usersession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
