# Generated by Django 4.1 on 2024-06-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_usersession_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
